project:
  type: book
  output-dir: docs
  
book:
  title: Research Guidelines
  subtitle: "OSAA Research Management Guide"
  page-footer:
    left: |
      Written by [Mirian Lima](mailto:mirian.lima@un.org) @<a href="https://www.un.org/osaa/">OSAA</a>
    right: |
      Built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: assets/cover.jpg
  downloads: pdf
  page-navigation: true
  favicon: assets/orange.png
  margin-header: |
    ![](/assets/identifier_color.png)
  site-url: https://mirianlima.github.io/research_guidelines/
  repo-url: https://github.com/mirianlima/research_guidelines
  repo-branch: master
  chapters:
    - index.qmd
    - executive-summary.qmd
    - part: Main Section
      chapters: 
        - chapters/introduction.qmd
        - chapters/preliminary-research.qmd
        - chapters/indepth-research.qmd
    - part: Appendix
      chapters:
        - appendix/survey.qmd
        - appendix/analysis_plan.qmd
        - appendix/inventory.qmd
        - appendix/editorial.qmd
        - appendix/annotated_biblio.qmd

format:
  html:
    code-link: true
    theme: 
      - cosmo
      - styles/research.scss
    toc: true
  pdf:
    documentclass: scrreprt

    author-meta: "Mirian Lima"
    callout-appearance: simple


